language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
env:
  - "HARNESS_OPTIONS=j9 TEST_ONLINE=mongodb://127.0.0.1:27017/minion"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
install:
  - "cpanm -n --installdeps ."
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
notifications:
  email: false
